# Generated by Django 4.0.3 on 2022-03-31 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='entity_ptr',
        ),
        migrations.DeleteModel(
            name='Beast',
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
