# Generated by Django 4.0.3 on 2022-03-31 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_item_entity_ptr_delete_beast_delete_entity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('membership_req', models.BooleanField(default=False)),
                ('type', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Beast',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.entity')),
                ('attack_style', models.CharField(default='', max_length=100)),
                ('weakness', models.CharField(default='', max_length=100)),
                ('life_points', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=0)),
            ],
            bases=('api.entity',),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.entity')),
                ('price', models.PositiveIntegerField(default=1)),
            ],
            bases=('api.entity',),
        ),
    ]
