from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
# In general for django, we want large models (put logic and functions here) and thin views

class Entity(models.Model):
    name = models.CharField(max_length=100)
    membership_req = models.BooleanField(default=False)
    type = models.PositiveSmallIntegerField() #determines if an Entity is an NPC (0), Beast (1), or Item (2)

class Beast(Entity):
    attack_style = models.CharField(max_length=100, default='')
    weakness = models.CharField(max_length=100, default='')
    life_points = models.PositiveIntegerField(default=0)
    level = models.PositiveIntegerField(default=0)

class Item(Entity):
    price = models.PositiveIntegerField(default=1)

# Usernames must be between 1 and 12 characters long. Usernames may only contain alphanumeric characters, the space, and hyphens (-). Any other characters are replaced with a space.
# https://runescape.wiki/w/Character_name#Limitations 
class Character(models.Model):
    name = models.CharField(max_length=12, unique=True)
    is_member = models.BooleanField(default=False)
    agility = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(120)])
    agility_xp = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(200_000_000)])
    archaeology = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(120)])
    archaeology_xp = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(200_000_000)])
    attack = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(120)])
    attack_xp = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(200_000_000)])
    constitution = models.IntegerField(default=10, validators=[MinValueValidator(1), MaxValueValidator(120)])
    constitution_xp = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(200_000_000)])
    construction = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(120)])
    construction_xp = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(200_000_000)])
    cooking = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(120)])
    cooking_xp = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(200_000_000)])
    crafting = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(120)])
    crafting_xp = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(200_000_000)])
    defence = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(120)])
    defence_xp = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(200_000_000)])
    divination = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(120)])
    divination_xp = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(200_000_000)])
    dungeoneering = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(120)])
    dungeoneering_xp = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(200_000_000)])
    farming = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(120)])
    farming_xp = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(200_000_000)])
    firemaking = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(120)])
    firemaking_xp = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(200_000_000)])
    fishing = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(120)])
    fishing_xp = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(200_000_000)])
    fletching = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(120)])
    fletching_xp = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(200_000_000)])
    herblore = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(120)])
    herblore_xp = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(200_000_000)])
    hunter = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(120)])
    hunter_xp = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(200_000_000)])
    invention = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(120)])
    invention_xp = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(200_000_000)])
    magic = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(120)])
    magic_xp = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(200_000_000)])
    mining = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(120)])
    mining_xp = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(200_000_000)])
    prayer = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(120)])
    prayer_xp = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(200_000_000)])
    ranged = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(120)])
    ranged_xp = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(200_000_000)])
    runecrafting = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(120)])
    runecrafting_xp = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(200_000_000)])
    slayer = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(120)])
    slayer_xp = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(200_000_000)])
    smithing = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(120)])
    smithing_xp = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(200_000_000)])
    strength = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(120)])
    strength_xp = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(200_000_000)])
    summoning = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(120)])
    summoning_xp = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(200_000_000)])
    thieving = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(120)])
    thieving_xp = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(200_000_000)])
    woodcutting = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(120)])
    woodcutting_xp = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(200_000_000)])